export * from "./Header";
export * from "./Main1";
export * from "./Main2";
export * from "./Skill";
export * from "./SkillIcon";
export * from "./Main3";
export * from "./Main4";
export * from "./Footer";
export * from "./Mobile";
